export const AuditAction = {
  // Auth
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',

  // Patient
  PATIENT_CREATED: 'PATIENT_CREATED',
  PATIENT_VIEWED: 'PATIENT_VIEWED',
  PATIENT_UPDATED: 'PATIENT_UPDATED',
  PATIENT_ARCHIVED: 'PATIENT_ARCHIVED',
  PATIENT_RESTORED: 'PATIENT_RESTORED',
  PATIENT_DELETED: 'PATIENT_DELETED',

  // Session
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_VIEWED: 'SESSION_VIEWED',
  SESSION_CANCELLED: 'SESSION_CANCELLED',
  SESSION_REMINDER_SENT: 'SESSION_REMINDER_SENT',

  // Admin / Profile
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  USER_ACCOUNT_DELETED: 'USER_ACCOUNT_DELETED',
} as const;
